### ISSUE TITLE
hello everyone . I'm making a chatbott following this link https://github.com/MrJay10/banking-faq-bot/issues. But now i have some problem . Can someone help me solve this 

### ISSUE THREAD

**Issue by syhuynh16897** [syhuynh16897/sy#1]
- [ ] Traceback (most recent call last):
  File "C:\Users\TechCare\Desktop\NCKH\new2\banking-faq-bot-master\Bank FAQbot.py", line 156, in <module>
    chat()
  File "C:\Users\TechCare\Desktop\NCKH\new2\banking-faq-bot-master\Bank FAQbot.py", line 111, in chat
    class_ = le.inverse_transform(model.predict(t_usr)[0])
  File "C:\Python\lib\site-packages\sklearn\preprocessing\label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "C:\Python\lib\site-packages\sklearn\utils\validation.py", line 760, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

**Comment by syhuynh16897** [comment]
can someone help me solve this problem ??
